---
# DotGit Sync Configuration
# ------------------------------------------------------------------------------
version: v1alpha1
dotgit:
  source:
    git:
      url: https://framagit.org/rdeville-public/programs/dotgit-sync-templates
      ref: main
  yaml:
    merge: &yaml
      method: only
      only:
        - .pre-commit-config.yaml
        - gitlab-ci.yaml
    enforce: *yaml
  json:
    merge: &json
      method: all
    enforce: *json

# Repos description and template usage configuration
# ------------------------------------------------------------------------------
name: OpenBao Identity
slug: openbao-identity
description: |-
  Deployment and management of Identity, Aliases and Auth Backend

licenses:
  date:
    first_year: "2025"
  copyright:
    Romain Deville: code@romaindeville.fr
  primary: MIT
  secondaries:
    - BEERWARE
maintainers:
  Romain Deville: code@romaindeville.fr
gitignore:
  templates:
    - base
  query:
    - terraform
templates:
  - base
  - base-ci-gitlab
  - base-pre-commit
  - commitlint-pre-commit
  - markdown
  - markdown-pre-commit
  - markdown-ci-gitlab
  - opentofu
  - opentofu-pre-commit
  - opentofu-ci-gitlab


# Everything below is only used as variables in templates
# ------------------------------------------------------------------------------
extra:
  code_of_conduct:
    abuse: abuse+code@romaindeville.fr
  maintainers:
    Romain Deville:
      socials:
        Website:
          alt: &website https://romaindeville.fr
          url: *website
        Github:
          alt: "@rdeville"
          url: https://github.com/rdeville
        Gitlab:
          alt: "@r.deville"
          url: https://gitlab.com/r.deville
        Framagit:
          alt: "@rdeville"
          url: https://framagit.org/rdeville
  repo:
    url: https://framagit.org/rdeville-public/opentofu/openbao-identity
