# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.8, < 2.0"

  required_providers {
    vault = {
      source  = "hashicorp/vault"
      version = "~>5.3"
    }
  }
}
